name: Daily Commit

on:
  schedule:
    - cron: '30 7 * * *'  # daily at 7:30 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit step by 22f3002355@ds.study.iitm.ac.in
        run: |
          echo "Daily heartbeat on $(date)" >> daily_log.txt
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "22f3002355@ds.study.iitm.ac.in"
          git add daily_log.txt
          git commit -m "Automated daily commit: $(date)" || echo "No changes to commit"
          git push
